"""empty message

Revision ID: 1f0d688d02cb
Revises: 93584ecf0601
Create Date: 2021-11-09 22:25:15.031328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0d688d02cb'
down_revision = '93584ecf0601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_in', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checked_in')
    # ### end Alembic commands ###
