"""empty message

Revision ID: 2855fe8d8e9f
Revises: 4e2c89b0b11a
Create Date: 2021-11-08 18:37:45.745705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2855fe8d8e9f'
down_revision = '4e2c89b0b11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
