"""empty message

Revision ID: 3577d3afa8df
Revises: 00ec5fa824fa
Create Date: 2021-11-09 15:14:17.238453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3577d3afa8df'
down_revision = '00ec5fa824fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=False))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'])
    op.alter_column('video', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('video', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('video', 'total_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'total_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('video', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'due_date')
    op.drop_column('rental', 'customer_id')
    op.alter_column('customer', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
