"""empty message

Revision ID: 732baa529f70
Revises: 00ec5fa824fa
Create Date: 2021-11-08 18:33:35.515356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732baa529f70'
down_revision = '00ec5fa824fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
